### ISSUE TITLE
Handling events on a client instance

### ISSUE THREAD

**Issue by Saphar** [wslyhbb/node-ldapjs-promise#6]
In the official ldapjs documentation it states the following:

> The client is an EventEmitter. If you don't register an error handler and e.g. a connection error occurs, Node.js will print a stack trace and exit the process ([reference](https://nodejs.org/api/events.html#error-events)).

But the client returned by this wrapper is not an EventEmitter. One would have to write:

```js
const client = ldap.createClient(...);

client.client.on("error", error => ...);
```

I missed this in the documentation. But better perhaps would be if there would be a more elegant solution to this. The instantiated client could return a promise?

**Comment by wslyhbb** [comment]
Does this solve your issue: #7?

**Comment by Saphar** [comment]
Yes, it does. Thank you for fixing this.
