### ISSUE TITLE
Fix return format for searchReturnAll

### ISSUE THREAD

**Issue by NikoHadouken** [wslyhbb/node-ldapjs-promise#9]
When `sizeLimit` is exceeded, only the entries are returned.

https://github.com/wslyhbb/node-ldapjs-promise/blob/99913e676a6be0a6466d50b9a4d88cd537983783/lib/client/index.js#L399

Return format should always have the shape `{ entries, referrals }`

**Comment by wslyhbb** [comment]
Valid point. Resolved in version 3.0.1.
